# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RxSubject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSubject
  
  # Utils
  pod 'Then'

  # UI
  pod 'SnapKit', '~> 4.0.0'
  pod 'UIBaseKit'

  # Rx
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'

  target 'RxSubjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSubjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
