# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ActionSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ActionSample
pod 'RxSwift'
pod 'Action'
pod 'NSObject+Rx'
end
